#-------------------------------
# Quarkus settings
#-------------------------------
quarkus:
  management:
    enabled: true
    port: 9001 
  grpc:
    codegen:
      skip: true
  arc:
#    remove-unused-beans: false
    remove-unused-beans: true
#    unremovable-types:
#      - hu.icellmobilsoft.coffee.module.csv.**
#      - hu.icellmobilsoft.coffee.tool.utils.stream.LoggingPublisher
#      - hu.icellmobilsoft.coffee.rest.validation.xml.utils.XsdHelper
#      - hu.icellmobilsoft.coffee.rest.validation.xml.error.XsdValidationErrorCollector
#      - hu.icellmobilsoft.coffee.rest.validation.catalog.PublicCatalogResolver
#      - hu.icellmobilsoft.coffee.module.mp.restclient.provider.DefaultLoggerClientRequestFilter
#      - hu.icellmobilsoft.coffee.module.mp.restclient.provider.DefaultLoggerClientResponseFilter
#      - hu.icellmobilsoft.coffee.module.mp.restclient.provider.DefaultSettingClientRequestFilter
  log:
    category:
      "hu.icellmobilsoft":
        level: ${SAMPLER_LOG_HU_ICELLMOBILSOFT_LEVEL:INFO}
    console:
      json: ${SAMPLER_LOG_CONSOLE_JSON_ENABLED:false}
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [traceId=%X{traceId}] [spanId=%X{spanId}] [thread:%t] [%c{10}] [sid:%X{extSessionId}] - %s%E%n"
    handler:
      gelf:
        additional-field:
          "moduleVersion":
            value: ${SAMPLER_LOGSTASH_MODULE_VERSION:unknown}
          "moduleId":
            value: ${SAMPLER_LOGSTASH_MODULE_ID:unknown}
          "K8S_NAMESPACE":
            value: ${SAMPLER_LOGSTASH_K8S_NAMESPACE:unknown}
        include-full-mdc: false
        enabled: ${SAMPLER_LOGSTASH_ENABLED:false}
        host: ${SAMPLER_LOGSTASTH_HOST:tcp:localhost}
        port: ${SAMPLER_LOGSTASTH_PORT:12201}
        version: ${SAMPLER_LOGSTASTH_VERSION:1.1}
    level: ${SAMPLER_LOG_LEVEL:INFO}
    min-level: ${SAMPLER_LOG_MIN_LEVEL:ALL}
  otel:
    exporter:
      otlp:
        endpoint: http://opentelemetry-collector:4317
  micrometer:
    export:
      otlp:
       url: http://opentelemetry-collector:4318/v1/metrics

  package:
    jar:
      type: fast-jar
      add-runner-suffix: false
  smallrye-openapi:
    info-title: Quarkus sampler service
    info-version: ${quarkus.application.version}
    info-description: >
      REST endpoints for operations. <br/> 
      General responses in case of error:  <br/> 
      * __400__ - Bad Request <br/> 
      * __401__ - Unauthorized <br/> 
      * __404__ - Not found <br/> 
      * __418__ - Database object not found <br/> 
      * __500__ - Internal Server Error <br/>
  swagger-ui:
    enable: false

