= Quarkus Sampler Documentation

image:https://img.shields.io/github/actions/workflow/status/i-Cell-Mobilsoft-Open-Source/quarkus-sampler/compile_maven.yml?branch=main&logo=GitHub&style=plastic[Compile status,link=https://github.com/i-Cell-Mobilsoft-Open-Source/quarkus-sampler/actions/workflows/compile_maven.yml?query=branch%3Amain]
image:https://img.shields.io/maven-central/v/hu.icellmobilsoft.quarkus.sampler/quarkus-sampler?logo=apache-maven&style=for-the-badge)[Maven central version of Parent pom project]
image:https://img.shields.io/github/license/i-Cell-Mobilsoft-Open-Source/quarkus-sampler?style=plastic&logo=apache[License of Parent pom project]
image:https://img.shields.io/badge/Use_JakartaEE_10+-project-brightgreen.svg?style=plastic&logo=jakartaee[Use JakartaEE project]
image:https://img.shields.io/github/commit-activity/m/i-Cell-Mobilsoft-Open-Source/quarkus-sampler.svg?label=Commits&style=plastic&logo=git&logoColor=white[Commits]
image:https://img.shields.io/badge/JVM-17--21-brightgreen.svg?style=plastic&logo=openjdk[Supported jvms]
image:https://img.shields.io/github/stars/i-Cell-Mobilsoft-Open-Source/quarkus-sampler?style=plastic[GitHub Repo Stars,link=https://github.com/i-Cell-Mobilsoft-Open-Source/quarkus-sample/stargazers]

== General

The project aims to provide a functional usage pattern for a general Quarkus project structure.

NOTE: Documentation: `https://i-cell-mobilsoft-open-source.github.io/quarkus-sampler/`

== Used technologies

* Coffee 2.0.0+ +
JavaEE solution set aimed at gathering common algorithms used in the enterprise world, providing basic solutions that can be customized to meet our specific needs (https://github.com/i-Cell-Mobilsoft-Open-Source/coffee) +

* Java 17+
* Maven 3.8.2+
* Jakarta EE 10+
* CDI 4.0+
* Microprofile 6.0+
* Quarkus 3.2.5.Final+
* Tracing with grafana


== Testing
The endpoints are not authenticated; you can use the SwaggerUI page.
Unfortunately, due to the complexity of the API, it won't work well in XML format because of XML namespace issues.
Therefore, it's better to use JSON format for this.

.Developer tests - qs-testsuite
`qs-testsuite`

The developer tests use the https://github.com/i-Cell-Mobilsoft-Open-Source/roaster[Roaster] project.
This performs completely autonomous REST external calls to the deployed application.
It can be run directly from the developer UI (JUnit plugin) or using Maven (by activating the 'profile' switch),
for example:

[source,bash]
----
mvn verify -Dprofile <1>
mvn verify -Dprofile=sandbox,local <2>
----
<1> default parameters
<2> Selected profiles from the configuration files


== Release

The release process is automated and managed by GitHub Actions.
In case of a release, not only a Maven release is prepared, but also Docker images for the sampler services.

./etc/release/Dockerfile
Fundamentally, it consists of three parts:

. Base image, which in our case is a Java 17 image.
. Downloading the JAR file - pulling the desired deployment file from Nexus.
. Finalizing the Docker image - including copying JAR files, etc.

./quarkus-sampler/etc/release/docker-compose.yml
Its function is to configure the variables of the services and manage them collectively.

