{
 "title": "Backend",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "base_jvm_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU load [%] / core",
   "type": "timeseries",
   "description": "https://scoutapm.com/blog/understanding-load-averages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent / base_cpu_availableProcessors",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 9 },
   "targets": [
    { "expr": "base_thread_count", "legendFormat": "Current" },
    { "expr": "base_thread_max_count", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "base_memory_usedHeap_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CG Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(base_gc_time_total_seconds[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}