{
 "title": "Backend_memory_usage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Generic memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory - maxHeap [MiB]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory - usedHeap [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC overhead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "rate(jvm_gc_overhead[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory - committedHeap [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - maxNonHeap [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{area=\"nonheap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - committedNonHeap [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{area=\"nonheap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - usedNonHeap [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "G1GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Memory - G1EdenSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"G1 Eden Space\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - G1OldGenUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"G1 Old Gen\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - G1SurvivalUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"G1 Survivor Space\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZGC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - ZHeapUsageUsage [MiB]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vendor_memoryPool_ZHeap_usage_bytes",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory - ZHeapUsageUsageMax [MiB]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vendor_memoryPool_ZHeap_usage_max_bytes",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SerialGC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - edenSpaceUsage [MiB]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vendor_memoryPool_Eden_Space_usage_bytes{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory - survivalSpaceUsage [MiB]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vendor_memoryPool_Survivor_Space_usage_bytes{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory - tenuredGenUsage [MiB]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vendor_memoryPool_Tenured_Gen_usage_bytes{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "ParallelGC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Memory - PSSurvivorSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"PS Survivor Space\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - PSEdenSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"PS Eden Space\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - PSOldGenSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"PS Old Gen\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}