{
 "title": "Backend",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_milliseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU load [%] / core",
   "type": "timeseries",
   "description": "https://scoutapm.com/blog/understanding-load-averages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Started Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 10 },
   "targets": [
    { "expr": "jvm_threads_started_total", "legendFormat": "Current" },
    { "expr": "base_thread_max_count", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "CG Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "rate(jvm_gc_overhead[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP active request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP requests sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "http_server_requests_milliseconds_sum",
     "legendFormat": "{{method}} {{uri}} status: {{status}}"
    }
   ]
  },
  { "title": "Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Agroal active count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "agroal_active_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Agroal available count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "agroal_available_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Agroal blocking time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "agroal_blocking_time_total_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agroal max used count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    { "expr": "agroal_max_used_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Trace data",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "filters": [
      { "id": "12412c5c", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": []
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}