{
 "title": "gRPC micrometer/telemetry",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "gRPC server metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gRPC request message received",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "grpc_server_requests_received_messages_total",
     "legendFormat": "{{method}}-{{methodType}}-{{service}}"
    }
   ]
  },
  {
   "title": "gRPC response message sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "grpc_server_responses_sent_messages_total",
     "legendFormat": "{{method}}-{{methodType}}-{{service}}"
    }
   ]
  },
  {
   "title": "gRPC server processing duration via status mean seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(grpc_server_processing_duration_milliseconds_sum[$__rate_interval])",
     "legendFormat": "{{method}}-{{methodType}}-{{service}}-{{status}}"
    }
   ]
  },
  { "title": "gRPC telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "gRPC telemetry",
   "type": "table",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "filters": [
      { "id": "e955f998", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}