version: "3.8"

services:
  mongodb:
    container_name: qs-mongodb
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - default

  mongosetup:
    image: mongo:7.0
    depends_on:
      - mongodb
    entrypoint: >
      bash -c "
        sleep 5 &&
        mongosh --host qs-mongodb:27017 --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"qs-mongodb:27017\" }]
          })
        '
      "
    networks:
      - default

networks:
  default:
    external:
      name: quarkus-sampler-local-network
