# from docker-compose
ARG ICELL_JAVA_JRE_BASE_IMAGE

FROM ${ICELL_JAVA_JRE_BASE_IMAGE}

ARG SERVICE
ENV SERVICE=${SERVICE}

COPY --chown=$SYSTEM_USER:$SYSTEM_USER_GROUP qs-services/$SERVICE/target/$SERVICE-0.1.0-SNAPSHOT $HOME/deployments/


EXPOSE 8080
EXPOSE 5005

CMD exec $HOME/deployments/$SERVICE-0.1.0-SNAPSHOT
