sampler:
    service:
        sample:
            base:
                uri: http://localhost:8080
        grpc:
            server:
              host: localhost
              port: 9000

testsuite:
  rest:
    sampleService:
      sample:
        baseUriKey: sampler.service.sample.base.uri
        path: /test/quarkusSamplerService/check
