version: "3.8"

# build start
# docker-compose -f quarkus-sampler/etc/release/docker-compose.yml build --no-cache
# running Docker in interactive mode
# docker run --rm -it icellmobilsoft/quarkus-sampler-qs-rest-service:0.1.0-SNAPSHOT /bin/sh
# image start
# docker run --rm -p 8080:8080 -p 9990:9990 icellmobilsoft/quarkus-sampler-qs-rest-service:0.1.0-SNAPSHOT

services:
  qs-rest-service-release:
    build:
      context: ../../
      dockerfile: etc/release/Dockerfile
      args:
        ICELL_JAVA_17_JRE_BASE_IMAGE: '$BASE_IMAGE'
        ARTIFACT_DOWNLOADER_IMAGE: '$ARTIFACT_DOWNLOADER_IMAGE'
        POM_GROUP_ID: 'hu.icellmobilsoft.quarkus.sampler'
        POM_ARTIFACT_ID: 'qs-rest-service'
        POM_EXTENSION: 'jar'
        # The CI scripts load the value of RELEASED_VERSION based on the started process.
        POM_VERSION: '$RELEASED_VERSION'
    image: "$DDOCKER_SERVICE_QUARKUS_SAMPLE_REST_SERVICE:$RELEASED_VERSION"
