#-------------------------------
# Coffee config
#-------------------------------
coffee:
  config:
    datasource:
      default:
        name: icellmobilsoftDS
#-------------------------------
# Quarkus settings
#-------------------------------
quarkus:
  datasource:
    "icellmobilsoftDS":
      jdbc:
        min-size: 5
        max-size: 20
        tracing:
          enabled: true
        telemetry:
          enabled: true
        url: jdbc:h2:mem:default
      db-kind: h2
  hibernate-orm:
    packages: hu.icellmobilsoft.quarkus.sampler.model
    datasource: "icellmobilsoftDS"
    dialect: org.hibernate.dialect.H2Dialect
    database:
      generation: drop-and-create
    log:
      #queries-slower-than-ms: 500
      format-sql: true
      sql: true
      #bind-parameters: true
    jdbc:
      timezone: UTC
    mapping:
      timezone:
        default-storage: normalize-utc
  arc:
    unremovable-types:
      - hu.icellmobilsoft.coffee.module.csv.**
      - org.apache.deltaspike.data.impl.handler.QueryHandler
      - hu.icellmobilsoft.coffee.tool.utils.stream.LoggingPublisher
      - hu.icellmobilsoft.coffee.rest.validation.xml.utils.XsdHelper
      - hu.icellmobilsoft.coffee.rest.validation.xml.error.XsdValidationErrorCollector
      - hu.icellmobilsoft.coffee.rest.validation.catalog.PublicCatalogResolver
  rest-client:
    "hu.icellmobilsoft.quarkus.sampler.rest.restclient.ITestSecondQuarkusSamplerServiceRestRegisteredClient":
      url: http://localhost:8080
      scope: jakarta.enterprise.context.ApplicationScoped
      #read-timeout: 5000
      #connect-timeout: 5000
    "hu.icellmobilsoft.quarkus.sampler.rest.restclient.ITestQuarkusSamplerServiceRestRegisteredClient":
      url: http://localhost:8080
      scope: jakarta.enterprise.context.ApplicationScoped
      #read-timeout: 5000
      #connect-timeout: 5000
  smallrye-openapi:
    info-title: Quarkus JPA sampler service
    info-version: ${quarkus.application.version}
    info-description: >
      REST endpoints for operations. <br/> 
      General responses in case of error:  <br/> 
      * __400__ - Bad Request <br/> 
      * __401__ - Unauthorized <br/> 
      * __404__ - Not found <br/> 
      * __418__ - Database object not found <br/> 
      * __500__ - Internal Server Error <br/>
  swagger-ui:
    enable: false

