= Quarkus Sampler Documentation

image:https://img.shields.io/github/actions/workflow/status/i-Cell-Mobilsoft-Open-Source/quarkus-sampler/compile_maven.yml?branch=main&logo=GitHub&style=plastic[Compile status,link=https://github.com/i-Cell-Mobilsoft-Open-Source/quarkus-sampler/actions/workflows/compile_maven.yml?query=branch%3Amain]
image:https://img.shields.io/maven-central/v/hu.icellmobilsoft.quarkus.sampler/quarkus-sampler?logo=apache-maven&style=for-the-badge)[Maven central version of Parent pom project]
image:https://img.shields.io/github/license/i-Cell-Mobilsoft-Open-Source/quarkus-sampler?style=plastic&logo=apache[License of Parent pom project]
image:https://img.shields.io/badge/Use_JakartaEE_10+-project-brightgreen.svg?style=plastic&logo=jakartaee[Use JakartaEE project]
image:https://img.shields.io/github/commit-activity/m/i-Cell-Mobilsoft-Open-Source/quarkus-sampler.svg?label=Commits&style=plastic&logo=git&logoColor=white[Commits]
image:https://img.shields.io/badge/JVM-17--21-brightgreen.svg?style=plastic&logo=openjdk[Supported jvms]
image:https://img.shields.io/github/stars/i-Cell-Mobilsoft-Open-Source/quarkus-sampler?style=plastic[GitHub Repo Stars, link=https://github.com/i-Cell-Mobilsoft-Open-Source/quarkus-sample/stargazers]

== General

The purpose of the project is to provide a working example for the general structure of a Quarkus project.

[NOTE]
====
Documentation: `https://i-cell-mobilsoft-open-source.github.io/quarkus-sampler/`
====

== Used technologies

* Coffee 2.0.0+ +
"Java EE solution set aimed at gathering common algorithms used in the enterprise world, providing fundamental solutions that can be customized to meet specific needs." (https://github.com/i-Cell-Mobilsoft-Open-Source/coffee) +

* Java 17+
* Maven 3.8.2+
* Jakarta EE 10+
* CDI 4.0+
* Microprofile 6.0+
* Quarkus 3.16.4+
* Tracing with grafana

== Projekt structure

* `/.github` - GitHub settings

* `/docs` - Repository of documentation

* `/etc` - Configurations, development environment scripts, etc.

** `/etc/config` - Configurations

*** `/etc/config/grafana/**` - Grafana dashboards, datasources.

*** `/etc/config/prometheus/**` - Prometheus configuration for localhost

** `/etc/docker-compose` - Docker Compose files and their corresponding Dockerfiles.

** `/etc/release` - Docker release management assistance in GitHub CI.
