= Useful commands and accesses

Commands used for development purposes,
which are used to build and start development environments.

The application can be started in several ways:

* Starting Quarkus dev with Maven
* Creating a Quarkus uber-jar and running this jar file using `java -jar`
** Placing the same jar into a Java Docker image and running it (using local.Dockerfile)
* Certain IDEs natively include a Quarkus project recognition module that automatically creates a run configuration, which can also be used to start the project.

Docker-compose is used for creating and running Docker images.

[NOTE]
====
The project includes a sampler-rest service that demonstrates the usage of the module.
This example can run entirely on a local development machine. Therefore, it has no external dependencies.
====

== Starting the qs-rest-service server in various ways

.IDE included Quarkus run config
----
Several browsers natively support Quarkus similarly to Spring Boot projects, recognizing it and creating their own run configurations.
----

.Maven quarkus:dev
----
mvn clean compile quarkus:dev
----

IMPORTANT: The project does not consist of a single module as Quarkus would expect, hence requiring compilation.

NOTE: Using the Quarkus Maven plugin, the project can be started in dev mode, activating several development tools. For more information: https://quarkus.io/guides/dev-mode-differences.

.Running Quarkus uber-jar in docker
----
mvn clean install <1>
docker-compose -f <PROJECT_PATH>/quarkus-sampler/etc/docker-compose/docker-compose.local.qs-rest-service.yml up --build --force-recreate <2>
----

<1> Therefore, it is necessary for the jar that goes into the Docker image to be built.
<2> Running the docker-compose command in the project root initiates the Docker Compose build (forcing recreation with the --force-recreate parameter if necessary) and starts up the services (up).

== qs-rest-service native

.Quarkus native
----
mvn install -Pnative -Dnative -Dquarkus.native.additional-build-args="--initialize-at-run-time=hu.icellmobilsoft.coffee.tool.utils.string.RandomUtil","--initialize-at-run-time=io.grpc.internal.RetriableStream","--initialize-at-run-time=hu.icellmobilsoft.coffee.se.util.string.RandomUtil","--add-opens java.base/java.net=ALL-UNNAMED"
----

.Quarkus native in docker
----
docker compose -f <PROJECT_PATH>/quarkus-sampler/etc/docker-compose/docker-compose.local.native.qs-rest-service.yml up --build --force-recreate
----