#-------------------------------
# Maven config
#-------------------------------
coffee:
  app:
    projectStage: dev
quarkus:
  otel:
    sdk:
      disabled: true
  micrometer:
    enabled: false
  log:
    level: INFO
    min-level: ALL
  #    handler:
  #      gelf:
  #        enabled: ${SAMPLER_LOGSTASH_ENABLED:true}
  swagger-ui:
    enable: true


