#-------------------------------
# Maven config
#-------------------------------
coffee:
  app:
    projectStage: dev
quarkus:
  log:
    level: INFO
    min-level: ALL
  swagger-ui:
    enable: true
