#-------------------------------
# Coffee config
#-------------------------------
coffee:
  app:
    name: ${quarkus.application.name}
  config:
    resource:
      bundles: i18n.messages
    xml:
      catalog:
        path: xsd/hu/icellmobilsoft/quarkus/sampler/dto/super.catalog.xml

mp:
  openapi:
    filter: hu.icellmobilsoft.quarkus.sampler.common.rest.filter.OpenAPIFilter

#-------------------------------
# Quarkus settings
#-------------------------------
quarkus:
  arc:
#    remove-unused-beans: false
    remove-unused-beans: true
  log:
    category:
      "hu.icellmobilsoft":
        level: ${SAMPLER_LOG_HU_ICELLMOBILSOFT_LEVEL:INFO}
    console:
      json: ${SAMPLER_LOG_CONSOLE_JSON_ENABLED:false}
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [thread:%t] [%c{10}] [sid:%X{extSessionId}] - %s%E%n"
    handler:
      gelf:
        additional-field:
          "moduleVersion":
            value: ${SAMPLER_LOGSTASH_MODULE_VERSION:unknown}
          "moduleId":
            value: ${SAMPLER_LOGSTASH_MODULE_ID:unknown}
          "K8S_NAMESPACE":
            value: ${SAMPLER_LOGSTASH_K8S_NAMESPACE:unknown}
        include-full-mdc: false
        enabled: ${SAMPLER_LOGSTASH_ENABLED:false}
        host: ${SAMPLER_LOGSTASTH_HOST:tcp:localhost}
        port: ${SAMPLER_LOGSTASTH_PORT:12201}
        version: ${SAMPLER_LOGSTASTH_VERSION:1.1}
    level: ${SAMPLER_LOG_LEVEL:INFO}
    min-level: ${SAMPLER_LOG_MIN_LEVEL:ALL}
  jaeger:
    sampler-type: ${SAMPLER_JAEGER_SAMPLER_TYPE:remote}
    sampler-manager-host-port: ${SAMPLER_JAEGER_SAMPLER_MANAGER_HOST_PORT:localhost:5778}
    reporter-log-spans: ${SAMPLER_JAEGER_REPORTER_LOG_SPANS:true}
    sampler-param: ${SAMPLER_JAEGER_SAMPLER_PARAM:1}
    enabled: ${SAMPLER_JAEGER_ENABLED:false}
  package:
    add-runner-suffix: false
#    type: uber-jar
    type: fast-jar
